### ISSUE TITLE
handle dns.resolver.LifetimeTimeout

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/baddns#376]
2023-08-24 04:24:55,910 [TRACE] bbot.scanner scanner.py:782 Traceback (most recent call last):                                                                 File "/root/bbot/bbot/scanner/scanner.py", line 730, in acatch                                                                                                 yield                                                                                                                                                      File "/root/bbot/bbot/modules/base.py", line 363, in _worker                                                                                                   await self.handle_event(event)                                                                                                                             File "/root/bbot/bbot/modules/baddns.py", line 21, in handle_event                                                                                             if await module_instance.dispatch():                                                                                                                       File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.10/lib/python3.10/site-packages/baddns/modules/ns.py", line 24, in dispatch                          await self.target_dnsmanager.dispatchDNS(omit_types=[["A", "AAAA", "MX", "NS", "SOA", "TXT"]])                                                             File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.10/lib/python3.10/site-packages/baddns/lib/dnsmanager.py", line 131, in dispatchDNS                  self.answers[rdatatype] = await self.do_resolve(self.target, rdatatype)                                                                                    File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.10/lib/python3.10/site-packages/baddns/lib/dnsmanager.py", line 116, in do_resolve                   r = self.process_answer(await self.dns_client.resolve(target, "CNAME"), "CNAME")                                                                           File "/root/bbot/bbot/core/helpers/dns.py", line 29, in resolve                                                                                                return await super().resolve(*args, **kwargs)                                                                                                              File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.10/lib/python3.10/site-packages/dns/asyncresolver.py", line 89, in resolve                           timeout = self._compute_timeout(start, lifetime, resolution.errors)                                                                                        File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.10/lib/python3.10/site-packages/dns/resolver.py", line 1075, in _compute_timeout                     raise LifetimeTimeout(timeout=duration, errors=errors)                                                                                                   dns.resolver.LifetimeTimeout: The resolution lifetime expired after 10.404 seconds: Server Do53:127.0.0.53@53 answered The DNS operation timed out after 4.98

**Comment by liquidsec** [comment]
This should be fixed, closing for now unless we see again.
