### ISSUE TITLE
Handle missing whoismanager.whois_result["data"]["expiration_date"]

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/baddns#379]
2023-08-24 22:37:09,089 [TRACE] bbot.scanner scanner.py:782 Traceback (most recent call last):
  File "/opt/bbot/bbot/scanner/scanner.py", line 730, in acatch
    yield
  File "/opt/bbot/bbot/modules/base.py", line 363, in _worker
    await self.handle_event(event)
  File "/opt/bbot/bbot/modules/baddns.py", line 22, in handle_event
    results = module_instance.analyze()
  File "/home/AMBERJACK/in3r9qut9b/.cache/pypoetry/virtualenvs/bbot-IFSyk-JB-py3.10/lib/python3.10/site-packages/baddns/modules/cname.py", line 203, in analyze
    expiration_data = self.cname_whoismanager.whois_result["data"]["expiration_date"]
KeyError: 'expiration_date'

**Comment by liquidsec** [comment]
should be fixed in https://github.com/blacklanternsecurity/baddns/pull/388
