### ISSUE TITLE
unhandled dnspython error

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/baddns#474]
/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/name.py:334:_validate_labels(): A DNS label is > 63 octets long.

2024-06-24 11:47:08,149 [ERROR] bbot.scanner scanner.py:1079 Error in baddns.handle_event(URL_UNVERIFIED("https://www.hyundaimobil.co.id/news/details/beli-hyundai-ioniq-5-hemat-hingga-rp...", module=excavate, tags={'endpoint', 'spider-danger', 'in-scope'})): /home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/name.py:334:_validate_labels(): A DNS label is > 63 octets long.
2024-06-24 11:47:08,151 [TRACE] bbot.scanner logger.py:83 Traceback (most recent call last):
  File "/home/liquid/bbot/bbot/scanner/scanner.py", line 1062, in _acatch
    yield
  File "/home/liquid/bbot/bbot/modules/base.py", line 629, in _worker
    await handle_event_task
  File "/home/liquid/bbot/bbot/modules/baddns.py", line 62, in handle_event
    if await task:
       ^^^^^^^^^^
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/baddns/modules/ns.py", line 37, in dispatch
    self.target_dnsmanager.answers["NS"] = await dnswalk.ns_trace(self.target)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/baddns/lib/dnswalk.py", line 49, in ns_trace
    solved_nameservers = await self.ns_recursive_solve(nameserver_ips, target, depth=0)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/baddns/lib/dnswalk.py", line 88, in ns_recursive_solve
    query_msg = dns.message.make_query(target, dns.rdatatype.NS)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/message.py", line 1787, in make_query
    qname = dns.name.from_text(qname, idna_codec=idna_codec)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/name.py", line 1063, in from_text
    return Name(labels)
           ^^^^^^^^^^^^
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/_immutable_ctx.py", line 40, in nf
    f(*args, **kwargs)
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/_immutable_ctx.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/name.py", line 373, in __init__
    _validate_labels(self.labels)
  File "/home/liquid/.cache/pypoetry/virtualenvs/bbot-N1wmp7PR-py3.11/lib/python3.11/site-packages/dns/name.py", line 334, in _validate_labels
    raise LabelTooLong
dns.name.LabelTooLong: A DNS label is > 63 octets long.

**Comment by liquidsec** [comment]
Fixed in #708
